import { Accordion, AccordionItem } from "./components/Accordion"
import Alert from "./components/Alert"
import allCities from "./components/allCities.json"
import Aside from "./components/Aside"
import Autocomplete from "./components/Autocomplete"
import Avatar from "./components/Avatar"
import { Breadcrumbs, BreadcrumbsItem } from "./components/Breadcrumbs"
import Burger from "./components/Burger"
import Button from "./components/Button"
import ButtonsContainer from "./components/ButtonsContainer"
import calculateTotalSum from "./components/calculateTotalSum"
import capitalize from "./components/capitalize"
import citiesGermany from "./components/citiesGermany.json"
import CodeContainer from "./components/CodeContainer"
