const pages = [
    "index",
    "colors",
    "fonts",
    "shadows",
    "container",
    "icon",
    "hr",
    "image",
    "video",
    "avatar",
    "button",
    "tag",
    "badge",
    "input",
    "buttons-container",
    "form",
    "loader",
    "breadcrumbs",
    "accordion",
    "dropdown",
    "toast",
    "card",
    "modal",
    "pagination",
    "progress-bar",
    "tabs",
    "slideshow",
    "alert",
    "burger",
    "title-flex",
    "page-loading",
    "messaging",
    "markdown-container",
]

export default pages
